name: primeira-pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  primeiro-job:
    name: 'Nome do Meu Primeiro Job'
    runs-on: ubuntu-latest
    steps:
      - name: 'Minha primeira ação'
        run: echo 'Hello World'
      - name: 'Minha segunda ação'
        run: |
          echo 'Você que criou seu primeiro workflow!!!'
          echo 'Parabéns!!!'
      - name: 'Minha terceira ação - Script Python'
        run: |
          variavel = "Hello World !!!"
          print(variavel)
        shell: python
  segundo-job: 
    name: "Segundo Job - Instalação do ambiente NodeJS"
    runs-on: ubuntu-latest
    needs: [primeiro-job]
    steps:
      - name: "Instalação do NodeJS"
        run: node --version
      - name: "Definição da versão 22.13.1"
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'
      - name: "Verificação da versão do NodeJS depois"
        run: node --version
